In [6]:
import numpy as np
import tensorflow as tf
xy = np.loadtxt('data-01-test-score.csv',delimiter = ',',dtype = np.float32)
x_data = xy[:, 0 :-1] # 시작부터 맨마지막 전 row 가져옴
y_data = xy[:,[-1]] #맨 마지막 row 가져옴
#print(x_data.shape,x_data, len(x_data))
#print(y_data.shape,y_data)

In [10]:
x = tf.placeholder(tf.float32,shape = [None,3])
y = tf.placeholder(tf.float32,shape = [None,1])

w = tf.Variable(tf.random_normal([3,1]),name = 'weight')
b = tf.Variable(tf.random_normal([1]),name = 'bias')

hypothesis = tf.matmul(x,w) + b
cost = tf.reduce_mean(tf.square(hypothesis - y))

In [13]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)
train = optimizer.minimize(cost)

In [15]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [17]:
for step in range(2001):
    cost_val, hy_val,_ = sess.run([cost,hypothesis,train],feed_dict = {x:x_data,y:y_data})
    if step % 10 == 0:
        print(step, "cost:",cost_val,"\nprediction:\n",hy_val)

0 cost: 51029.8 
prediction:
 [[-52.51709747]
 [-73.12968445]
 [-66.70490265]
 [-74.75257874]
 [-56.56840897]
 [-46.21292114]
 [-56.34597015]
 [-42.00151062]
 [-73.28572083]
 [-73.49032593]
 [-55.10894012]
 [-59.59124756]
 [-66.91356659]
 [-53.30258942]
 [-58.34046173]
 [-75.30136108]
 [-51.314991  ]
 [-66.58992004]
 [-61.91677094]
 [-54.72025681]
 [-66.72543335]
 [-70.0473175 ]
 [-62.16994858]
 [-48.25034332]
 [-73.2062912 ]]
10 cost: 58.8406 
prediction:
 [[ 158.26654053]
 [ 180.26213074]
 [ 182.93952942]
 [ 197.14405823]
 [ 136.68409729]
 [  96.29303741]
 [ 147.18650818]
 [ 108.89530182]
 [ 163.55661011]
 [ 145.9206543 ]
 [ 140.98347473]
 [ 133.78749084]
 [ 190.98925781]
 [ 161.07217407]
 [ 146.13658142]
 [ 181.84136963]
 [ 152.84602356]
 [ 177.66691589]
 [ 183.94671631]
 [ 165.26634216]
 [ 171.95046997]
 [ 167.67958069]
 [ 165.3802948 ]
 [ 164.23617554]
 [ 189.39025879]]
20 cost: 55.9622 
prediction:
 [[ 159.69247437]
 [ 182.02470398]
 [ 184.64985657]
 [ 199.02182007]
 [ 138.027999

In [21]:
print("your score will be", sess.run(hypothesis,feed_dict= {x :[[100,70,101]]}))
print("your score will be", sess.run(hypothesis,feed_dict= {x :[[60,70,110],[90,100,80]]}))


your score will be [[ 174.89570618]]
your score will be [[ 164.15905762]
 [ 184.98590088]]
